language: python

python : 3.7

install : python -m pip3 install --upgrade pip
          pip3 install pyqt5==5.15.1
          pip3 install openpyxl
          pip3 install pandas
          pip3 install numpy
          pip3 install sklearn
         
          

script : python TDD_GUI_Setting.py


after_success:
  - codecov
