language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.7"

virtualenv:
  system_site_packages: true

install:
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5
 - sudo apt-get -y install openpyxl
 - sudo apt-get -y install pandas
 - sudo apt-get -y install numpy
 - sudo apt-get -y install sklearn


