language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install pyqt5
  - pip install openpyxl
  - pip install pandas
  - pip install numpy
  - pip install sklearn
# command to run tests
script:
  - python TDD_GUI_Setting.py
 
after_success:
  - codecov
